# Generated by Django 5.2.6 on 2025-10-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_fix_message_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'chat_conversation_participants',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
