# Generated by Django 5.2.6 on 2025-09-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FOR_ADOPTION', 'For Adoption'), ('LOST', 'Lost'), ('FOUND', 'Found'), ('ADOPTED', 'Adopted/Reunited')], default='FOR_ADOPTION', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('RABBIT', 'Rabbit'), ('OTHER', 'Other')], max_length=10)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='pet_images/')),
                ('location', models.CharField(help_text='e.g., City, State or Neighborhood', max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
