# Generated by Django 5.2.6 on 2025-10-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_add_lost_fields'),
    ]

    operations = [
        # No-op migration: fields referenced previously are not present in the model state
        # Left intentionally empty to avoid migration state errors in local development.
    ]
