# Generated by Django 5.2.6 on 2025-10-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_add_lost_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='lost_datetime',
        ),
        migrations.RemoveField(
            model_name='petregistrationrequest',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='petregistrationrequest',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='petregistrationrequest',
            name='lost_datetime',
        ),
    ]
